name: SpaceTracer
channels:
  - conda-forge
  - anaconda
  - bioconda
  - r
dependencies:
  - python=3.9
  - numpy=1.24.3
  - pandas=1.5.3
  - scikit-learn
  - matplotlib=3.5.0
  - scipy=1.11.3
  - seaborn=0.13.0
  - samtools
  - bedtools
  - vcftools
  - geopandas=0.14.0
  - r-base
  - pip=21.2.4
  - r-pracma
  - r-dplyr
  - snakemake=3.13.3

  - pip:
    - colorcet==3.0.1
    - GraphST
    - hyperopt
    - imblearn
    - imbalanced_learn
    - SpaGCN==1.2.7
    - vcfpy==0.13.6
    - torch
    - esda==2.5.0
    - wordcloud
    - joblib==1.3.2
    - opencv_python
    - pybedtools==0.9.1
    - pyfaidx==0.7.2.2
    - pysal==23.07
    - pysam==0.22.0
    - scanpy==1.10.2
    - tqdm==4.66.1