name: SpaceTracer
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - numpy=1.26
  - pandas>=1.5
  - scikit-learn>=1.3
  - matplotlib>=3.5
  - scipy>=1.11
  - seaborn>=0.13
  - samtools
  - bedtools
  - bcftools
  - geopandas>=0.14
  - r-base
  - r-pracma
  - r-dplyr
  - r-extraDistr
  - r-tidyr
  - r-deconstructsigs
  - snakemake>=7.25
  - pytorch
  - torchvision
  - torchaudio
  - joblib>=1.3
  - tqdm>=4.66
  - biopython>=1.79 